version: '1'

services:
  mysql_db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fixes_db
      - MYSQL_ROOT_PASSWORD=fixes_password

  fixes_web:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    restart: always
    command: deploy/start-server.sh
    volumes:
      - .:/fixes_web
    ports:
      - "8000:8000"
    # need to use this env file to create a superuser in django when you first time run docker compose.
    # env_file:
      # - ./deploy/env_local
    depends_on:
      - mysql_db
